name: Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Plan
      id: plan
      run: |
        terraform plan -no-color
        echo "TF_PLAN=$(terraform plan -no-color)" >> $GITHUB_ENV

    - name: Update README
      run: |
        PLAN_OUTPUT="${{ env.TF_PLAN }}"
        READ_ME=$(cat README.md)
        UPDATED_READ_ME="${READ_ME/Última ejecución: (aquí se actualizará el estado)/Última ejecución: $PLAN_OUTPUT}"
        echo "$UPDATED_READ_ME" > README.md
        git config --global user.name 'Your Name'
        git config --global user.email 'your-email@example.com'
        git add README.md
        git commit -m "Actualizar README con el estado de Terraform"
        git push
