name: Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Plan
      id: plan
      run: |
        terraform init
        if terraform plan -no-color; then
          echo "PLAN_STATUS=success" >> $GITHUB_ENV
        else
          echo "PLAN_STATUS=failed" >> $GITHUB_ENV
        fi

    - name: Update README
      if: always()
      run: |
        PLAN_STATUS="${{ env.PLAN_STATUS }}"
        BADGE_URL="https://img.shields.io/badge/Terraform-Plan-${PLAN_STATUS}-brightgreen"
        sed -i "s|![Terraform Plan Status].*|![Terraform Plan Status](${BADGE_URL})|" README.md
        git config --global user.name 'Automation'
        git config --global user.email 'automation@bot.com'
        git add README.md
        git commit -m "Actualizar README con el estado de Terraform [skip ci]"
        git push
