name: Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Terraform Plan
      id: plan
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      run: |
        terraform plan

    - name: Update README
      run: |
        PLAN_OUTPUT="${{ steps.plan.outputs.stdout }}"
        READ_ME=$(cat README.md)
        UPDATED_READ_ME="${READ_ME/Última ejecución: (aquí se actualizará el estado)/Última ejecución: $PLAN_OUTPUT}"
        echo "$UPDATED_READ_ME" > README.md
        git config --global user.name 'Automation Bot'
        git config --global user.email 'automation@automation.com
        git commit -am "Actualizar README con el estado de Terraform [skip ci]"
        git push
